from agents import (
    build_search_agent,
    build_reader_agent,
    writer_chain,
    critic_chain
)


def extract_agent_text(result):
    """
    Extract the final text response from a LangChain agent result.
    """

    messages = result.get("messages", [])

    if not messages:
        return "No response generated by the agent."

    # Find the latest AI message containing text
    for message in reversed(messages):

        content = getattr(message, "content", None)

        if isinstance(content, str) and content.strip():
            return content

    return "No readable response generated."


def run_research_pipeline(topic: str) -> dict:

    state = {}

    # ========================================================
    # STEP 1 - SEARCH AGENT
    # ========================================================

    print("\n" + "=" * 60)
    print("STEP 1 - SEARCH AGENT")
    print("=" * 60)

    search_agent = build_search_agent()

    search_result = search_agent.invoke({
        "messages": [
            (
                "user",
                f"""
Find recent, reliable and detailed information
about the following research topic:

{topic}

Use the web_search tool.
"""
            )
        ]
    })

    state["search_results"] = extract_agent_text(
        search_result
    )

    print("\nSearch Results:\n")
    print(state["search_results"])


    # ========================================================
    # STEP 2 - READER AGENT
    # ========================================================

    print("\n" + "=" * 60)
    print("STEP 2 - READER AGENT")
    print("=" * 60)

    reader_agent = build_reader_agent()

    reader_result = reader_agent.invoke({
        "messages": [
            (
                "user",
                f"""
Research topic:
{topic}

Below are the search results:

{state["search_results"]}

Identify the most relevant URLs from these results
and use the scrape_url tool to read the most useful
web pages.

Extract detailed and relevant information that can
be used to write the final research report.
"""
            )
        ]
    })

    state["scraped_content"] = extract_agent_text(
        reader_result
    )

    print("\nScraped Content:\n")
    print(state["scraped_content"])


    # ========================================================
    # STEP 3 - WRITER CHAIN
    # ========================================================

    print("\n" + "=" * 60)
    print("STEP 3 - WRITER CHAIN")
    print("=" * 60)

    research_combined = (
        f"""
SEARCH RESULTS:

{state["search_results"]}


SCRAPED CONTENT:

{state["scraped_content"]}
"""
    )

    state["report"] = writer_chain.invoke({
        "topic": topic,
        "research": research_combined
    })

    print("\nFinal Research Report:\n")
    print(state["report"])


    # ========================================================
    # STEP 4 - CRITIC CHAIN
    # ========================================================

    print("\n" + "=" * 60)
    print("STEP 4 - CRITIC CHAIN")
    print("=" * 60)

    state["feedback"] = critic_chain.invoke({
        "report": state["report"]
    })

    print("\nCritic Feedback:\n")
    print(state["feedback"])


    return state


# ============================================================
# MAIN
# ============================================================

if __name__ == "__main__":

    topic = input(
        "\nEnter a research topic: "
    )

    result = run_research_pipeline(topic)